### PR TITLE
Support fetch feature in custom_script builder

### PR DESCRIPTION
**Pull request by dsemenets**

### CODE REVIEW

**Comment by dsemenets** [comment]
Actually this PR consists only one commit https://github.com/xen-troops/moulin/pull/104/commits/7a3cfa109c0e59369f633a6b87c498164f778857
Remain commits reviewed in PR https://github.com/xen-troops/moulin/pull/103

**Comment by lorc** [comment]
I believe you mistaken this issue with #100

**Comment by dsemenets** [comment]
> I believe you mistaken this issue with #100

No. I have updated this PR

**Comment by lorc** [comment]
Could you please elaborate what exactly your change does? It is hard to tell from the diff itself.

**Comment by dsemenets** [comment]
> Could you please elaborate what exactly your change does? It is hard to tell from the diff itself.
Fetcher creates directory 'build_dir' and fetch repository there. My changes moves config file for script and working directory to the 'build_dir'

**Comment by lorc** [comment]
I am curious if it will break existing scripts.

@Mishytca, @al1img, @svlad-90, AFAIR some of you are using this feature. Could you please check if this PR breaks your use case? It basically changes CWD for the script and this may or may not affect your scripts

**Comment by Mishytca** [comment]
Hi @lorc, I've performed the following steps:

- synced the target version of moulin
- checked, that my product contains at least one used 'custom_scipt' builder
- regenerated the build.ninja and incrementally rebuilt the product 

The result of the build is successful. So, I guess, you can merge it.

**Comment by lorc** [comment]
Thanks!

`Acked-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

@dsemenets please rebase this PR

**Comment by dsemenets** [comment]
@lorc I have added one more patch to fix tests. Please review

**Comment by lorc** [comment]
Could you please rearrange the commits so fix for test comes first and then change to "custom_script". This is to ensure that `git bisect` will behave correctly. 

With that:

`Acked-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

**Pull request merged**
