### PR TITLE
builders: fix `zephyr` builder

### PR DESCRIPTION
**Pull request by rshym**
For correct build we need to set proper environment.

Fixes: b42ac8cb54ebf8b5d9842985e1f127db47bdea0c

### CODE REVIEW

**Comment by rshym** [comment]
The original commit (this PR fixes that), was tested within an incorrect environment. So the important part was skipped.

For now, the build was tested inside a clean environment, to be sure that the `zephyr` builder sets up all required things.

**Comment by rshym** [comment]
@lorc could you please look at this PR?

**Comment by lorc** [comment]
`Acked-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

**Comment by rshym** [comment]
`Ack` is added.
Tested (see the second comment).
Ready to be merged.

**Pull request merged**
