### PR TITLE
Correct typo in "About Moulin" section

### PR DESCRIPTION
**Pull request by pahmann**
Changing "is" to "it" correcting a typo

### CODE REVIEW

**Comment by lorc** [comment]
Hi @pahmann.

Thank you for the contribution.
Please add the following tag to your commit message and I'll merge it:

`Reviewed-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

**Comment by pahmann** [comment]
Hi @lorc 

thanks, I will take care.

**Comment by lorc** [comment]
Oh, and by the way, could you please add your `Signed-off-by` tag?

This tag basically signifies that you are the author and you are okay that your changes will be used by other people (you can check [this link](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/process/submitting-patches.rst?h=v6.0-rc4#n379) for more information)

You can do this with `git commit --amend -s`

**Comment by pahmann** [comment]
@lorc thanks. I will add both signed-off and reviewed-by. I am currently on travel, so I hope you can be patient for a few more days, until I am back to my Linux workstation.

**Comment by lorc** [comment]
Hi @pahman,

Yeah, no problem at all.

**Comment by pahmann** [comment]
@lorc I hope the PR looks like you expected. I did a force push to overwrite the old commit message.

**Pull request merged**
